import Foundation
import Testing
import MusicDomain
import MusicPersistence
@testable import MusicApplication

@Suite("Playlist browse contents")
@MainActor
struct PlaylistBrowseIntegrationTests {
    @Test("Track status reads stored asset/root state and leaves offline references unchanged")
    func recordedAvailability() async throws {
        let directory = FileManager.default.temporaryDirectory.appending(path: "PlaylistStatus-\(UUID())")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let database = try MusicDatabase(url: directory.appending(path: "fixture.sqlite"))
        try await database.migrate()
        let root = try await database.createStorageRoot(.init(displayName: "Synthetic audio-free root", lastKnownPath: directory.path, bookmarkData: nil))
        try await database.updateStorageRootAccess(root.id, status: .available)
        let batch = try await database.createImportBatch(storageRootID: root.id, sourceDescription: "Fixture")
        try await database.recordImportCandidate(batchID: batch.id, payload: .init(relativePath: "not-a-real-audio.flac", fileName: "not-a-real-audio.flac", contentTypeIdentifier: "org.xiph.flac", fileSize: 1, modifiedAt: nil))
        let candidate = try #require(await database.importCandidates(batchID: batch.id).first)
        try await database.saveEmbeddedMetadata(.init(title: "Synthetic", albumTitle: "Album", artist: nil, albumArtist: nil, discNumber: 1, trackNumber: 1, durationMilliseconds: 1000, rawTags: [:]), for: candidate.id)
        try await database.rebuildImportReleaseProposals(batchID: batch.id, drafts: [.init(title: "Album", artist: nil, discCount: 1, confidence: 1, candidateIDs: [candidate.id])])
        let proposal = try #require(await database.importReleaseProposals(batchID: batch.id).first)
        let albumID = try await database.confirmImportReleaseProposal(proposal.id)
        let assetID = try #require(await database.digitalAssetIDs(albumID: albumID).first)
        try await database.updateAssetAvailability(assetID, to: .available)
        let revision = try await database.currentRevision()
        let available = try #require(await database.trackBrowseSummaries().first)
        #expect(available.audioStatus == .available) // No actual file exists; this is recorded status only.
        #expect(try await database.currentRevision() == revision)
        try await database.updateStorageRootAccess(root.id, status: .permissionRequired)
        #expect(try await database.trackBrowseSummaries().first?.audioStatus == .permissionRequired)
        try await database.updateStorageRootAccess(root.id, status: .available)
        try await database.updateAssetAvailability(assetID, to: .missing)
        #expect(try await database.trackBrowseSummaries().first?.audioStatus == .unavailable)
        try await database.updateStorageRootAccess(root.id, status: .offline)
        let offlineRevision = try await database.currentRevision()
        #expect(try await database.trackBrowseSummaries().first?.audioStatus == .offline)
        #expect(try await database.playbackAsset(trackID: available.id)?.availability == .missing)
        #expect(try await database.digitalAssetIDs(albumID: albumID) == [assetID])
        #expect(try await database.currentRevision() == offlineRevision)
    }

    @Test("Track picker metadata stays read-only, full-catalogue and active, with duplicate adds")
    func trackPicker() async throws {
        let directory = FileManager.default.temporaryDirectory.appending(path: "PlaylistPicker-\(UUID())")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let database = try MusicDatabase(url: directory.appending(path: "fixture.sqlite"))
        try await database.migrate()
        let album = try await database.createAlbum(.init(title: "Fixture Album"))
        let disc = try await database.createDisc(albumID: album.id)
        let track = try await database.createTrack(discID: disc.id, draft: .init(title: "Opening", durationMilliseconds: 123456))
        let untimed = try await database.createTrack(discID: disc.id, draft: .init(title: "Finale"))
        let playlist = try await database.createPlaylist(name: "Listening")
        let revision = try await database.currentRevision()
        let summaries = try await database.trackBrowseSummaries()
        #expect(summaries.map(\.id) == [track.id, untimed.id])
        let summary = try #require(summaries.first)
        #expect(summary.albumID == album.id && summary.albumTitle == album.title)
        #expect(summary.discNumber == 1 && summary.trackNumber == 1)
        #expect(summary.durationLabel == "2:03" && summaries[1].durationLabel == nil)
        #expect(summary.matches(" opening ", albumArtist: nil))
        #expect(summary.matches("fixture", albumArtist: nil))
        #expect(summary.matches("orchestra", albumArtist: "Fixture Orchestra"))
        #expect(!summary.matches("missing", albumArtist: nil))
        #expect(try await database.currentRevision() == revision)
        let store = LibraryStore(database: database)
        try await store.reload()
        await store.search("not-an-album")
        #expect(store.albums.isEmpty && store.trackBrowseSummaries == summaries)
        let entryID = UUID()
        try await store.addTrack(track.id, toPlaylist: playlist.id, itemID: entryID)
        let addedRevision = try await database.currentRevision()
        try await store.addTrack(track.id, toPlaylist: playlist.id, itemID: entryID)
        #expect(try await database.currentRevision() == addedRevision)
        await #expect(throws: DatabaseError.self) { try await store.addTrack(untimed.id, toPlaylist: playlist.id, itemID: entryID) }
        #expect(try await database.currentRevision() == addedRevision)
        try await store.addTrack(track.id, toPlaylist: playlist.id)
        #expect(store.playlistContents[playlist.id]?.count == 2)
        try await database.softDeleteAlbum(album.id)
        try await store.reload()
        #expect(store.trackBrowseSummaries.isEmpty)
        let deletedRevision = try await database.currentRevision()
        await #expect(throws: DatabaseError.self) { try await store.addTrack(track.id, toPlaylist: playlist.id) }
        #expect(try await database.currentRevision() == deletedRevision)
        #expect(try await database.playlistItems(playlistID: playlist.id).count == 2)
        try await database.restoreAlbum(album.id)
        try await store.reload()
        #expect(store.trackBrowseSummaries == summaries)
        #expect(store.storageRoots.isEmpty)
    }

    @Test("Batched contents preserve duplicate entries and refresh independently of album search")
    func contents() async throws {
        let directory = FileManager.default.temporaryDirectory.appending(path: "PlaylistBrowse-\(UUID())")
        try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(at: directory) }
        let database = try MusicDatabase(url: directory.appending(path: "fixture.sqlite"))
        try await database.migrate()
        let album = try await database.createAlbum(.init(title: "Fixture"))
        let disc = try await database.createDisc(albumID: album.id)
        let track = try await database.createTrack(discID: disc.id, draft: .init(title: "Track"))
        let playlist = try await database.createPlaylist(name: "Listening")
        let empty = try await database.createPlaylist(name: "Empty")
        try await database.addTrack(track.id, to: playlist.id)
        try await database.addTrack(track.id, to: playlist.id)
        let revision = try await database.currentRevision()
        let entries = try #require(try await database.playlistContents()[playlist.id])
        #expect(entries.count == 2 && entries[0].id != entries[1].id)
        #expect(entries.map(\.trackID) == [track.id, track.id])
        #expect(try await database.currentRevision() == revision)
        let store = LibraryStore(database: database)
        try await store.reload()
        await store.search("No matching albums")
        #expect(store.albums.isEmpty)
        #expect(store.playlistContents[playlist.id] == entries)
        #expect((store.playlistContents[empty.id] ?? []).isEmpty)
        try await store.movePlaylistItem(entries[1].id, to: 1)
        #expect(store.playlistContents[playlist.id]?.map(\.id) == [entries[1].id, entries[0].id])
        try await store.removePlaylistItem(entries[0].id)
        #expect(store.playlistContents[playlist.id]?.map(\.id) == [entries[1].id])
        #expect(try await database.track(id: track.id) != nil)
        try await store.deletePlaylist(playlist.id)
        #expect(store.playlistContents[playlist.id] == nil)
        try await store.restorePlaylist(playlist.id)
        #expect(store.playlistContents[playlist.id]?.count == 1)
        #expect(store.storageRoots.isEmpty)
    }
}
